### ISSUE TITLE
add fast sha2 to julia stdlib

### ISSUE THREAD

**Issue by gdkrmr** [JuliaCrypto/SHA.jl#58]
@staticfloat, now that the stress of the 1.0 release has passed, please don't forget to add the fast sha2 implementation to the SHA version in Stdlib.

**Comment by staticfloat** [comment]
@kristofferc what's the best way to get improvements from `SHA.jl` merged into stdlib?

**Comment by staticfloat** [comment]
And with https://github.com/JuliaLang/julia/pull/41370 we've finally come full circle.
