### ISSUE TITLE
Is there any interest in adding the SHA512/224 and SHA512/256 algorithms?

### ISSUE THREAD

**Issue by pixel27** [JuliaCrypto/SHA.jl#61]
I would be happy to do the work, I figure the module would end up exporting the following new objects:

- sha512_256
- sha2_512_256
- SHA2_512_256_CTX

and

- sha512_224
- sha2_512_224
- SHA2_512_224_CTX

The algorithms appear to mostly be the SHA512 with a different initial hash value. Does that seem reasonable?

**Comment by staticfloat** [comment]
Sure, PR's are welcome!

**Comment by mukul-mehta** [comment]
Hi, could I work on the issue?
