### ISSUE TITLE
Remove `Base.getproperty`

### ISSUE THREAD

**Issue by inkydragon** [JuliaCrypto/SHA.jl#77]
After removing `Base.getproperty`, you need to check if the exported API is type stable and how the performance changes.

https://github.com/JuliaCrypto/SHA.jl/blob/918aff1fd132034d19a940894106db2c97d8e977/src/types.jl#L42-L54

https://github.com/JuliaCrypto/SHA.jl/blob/918aff1fd132034d19a940894106db2c97d8e977/src/types.jl#L90-L102

**Comment by nandoconde** [comment]
@staticfloat I think it is safe to close this based on the linked PR :D

**Comment by inkydragon** [comment]
> it is safe to close this

Nope, `Base.getproperty` is still in the code base.

> > We may need to check the type stability and performance of each API after removing getproperty.
> > I will open a new issue to track this. (77)

This issue is opened after pr 75.
